"""simplify_user_model

Revision ID: 3c1948ff31a6
Revises: 27c7abb12359
Create Date: 2025-09-08 13:52:08.700894

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c1948ff31a6'
down_revision: Union[str, None] = '27c7abb12359'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_account_id', table_name='user')
    op.drop_index('ix_user_oauth_name', table_name='user')
    op.drop_constraint('user_user_id_fkey', 'user', type_='foreignkey')
    op.drop_column('user', 'access_token')
    op.drop_column('user', 'refresh_token')
    op.drop_column('user', 'account_id')
    op.drop_column('user', 'user_id')
    op.drop_column('user', 'expires_at')
    op.drop_column('user', 'account_email')
    op.drop_column('user', 'oauth_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('oauth_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.add_column('user', sa.Column('account_email', sa.VARCHAR(length=320), autoincrement=False, nullable=False))
    op.add_column('user', sa.Column('expires_at', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False))
    op.add_column('user', sa.Column('account_id', sa.VARCHAR(length=320), autoincrement=False, nullable=False))
    op.add_column('user', sa.Column('refresh_token', sa.VARCHAR(length=1024), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('access_token', sa.VARCHAR(length=1024), autoincrement=False, nullable=False))
    op.create_foreign_key('user_user_id_fkey', 'user', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_index('ix_user_oauth_name', 'user', ['oauth_name'], unique=False)
    op.create_index('ix_user_account_id', 'user', ['account_id'], unique=False)
    # ### end Alembic commands ###
