"""Add User model

Revision ID: 8a081dad6249
Revises: 3a35e6b1e1ed
Create Date: 2025-05-30 14:54:07.640312

"""
from typing import Sequence, Union
from fastapi_users_db_sqlalchemy.generics import GUID

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8a081dad6249'
down_revision: Union[str, None] = '3a35e6b1e1ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('id', GUID(), nullable=False),
    sa.Column('user_id', GUID(), nullable=False),
    sa.Column('oauth_name', sa.String(length=100), nullable=False),
    sa.Column('access_token', sa.String(length=1024), nullable=False),
    sa.Column('expires_at', sa.Integer(), nullable=True),
    sa.Column('refresh_token', sa.String(length=1024), nullable=True),
    sa.Column('account_id', sa.String(length=320), nullable=False),
    sa.Column('account_email', sa.String(length=320), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_account_id'), 'user', ['account_id'], unique=False)
    op.create_index(op.f('ix_user_oauth_name'), 'user', ['oauth_name'], unique=False)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_oauth_name'), table_name='user')
    op.drop_index(op.f('ix_user_account_id'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
