"""Add user_id to Recording

Revision ID: a4f7d1938aec
Revises: 8a081dad6249
Create Date: 2025-05-30 16:18:30.924452

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a4f7d1938aec'
down_revision: Union[str, None] = '8a081dad6249'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recordings', sa.Column('user_id', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'recordings', 'user', ['user_id'], ['id'])
    op.alter_column('user', 'username',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'username',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_constraint(None, 'recordings', type_='foreignkey')
    op.drop_column('recordings', 'user_id')
    # ### end Alembic commands ###
