"""add_job_context_to_questions

Revision ID: e4997e653ead
Revises: 3c1948ff31a6
Create Date: 2025-09-08 14:34:51.799553

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e4997e653ead'
down_revision: Union[str, None] = '3c1948ff31a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('job_title', sa.String(), nullable=True))
    op.add_column('questions', sa.Column('job_description', sa.Text(), nullable=True))
    op.add_column('questions', sa.Column('is_generated', sa.Boolean(), nullable=True))
    op.add_column('questions', sa.Column('created_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('questions', 'created_at')
    op.drop_column('questions', 'is_generated')
    op.drop_column('questions', 'job_description')
    op.drop_column('questions', 'job_title')
    # ### end Alembic commands ###
